### ISSUE TITLE
Image upload not working

### ISSUE THREAD

**Issue by Comicsy** [electricomics/generator#2]
I can click add image, select a file (png/jpg) and can click the upload button. The box appears below but it has no dimensions and the preview image doesn't appear. Can be dragged to main section but no picture appears.
![screen](https://cloud.githubusercontent.com/assets/14311310/9928236/c67ff3ba-5d1c-11e5-8ab8-0bc62b6ac815.jpg)
Using Windows 7.

**Comment by LeahMoore** [comment]
it does the same for me.

**Comment by ocasta** [comment]
Fixed in v1.0.1
